### ISSUE TITLE
Crash when provisioner source and content are null

### ISSUE THREAD

**Issue by RLRabinowitz** [opentofu/opentofu#1360]
### OpenTofu Version

```shell
1.6.2
```

### OpenTofu Configuration Files

```hcl
variable "aaa" {
  default = null
}

resource "null_resource" "a" {
  provisioner "file" {
    source = var.aaa
    destination = "aaa.jar"

    connection {
      host = "localhost"
    }
  }
}
```

### Debug Output

.

### Expected Behavior

No crash

### Actual Behavior

Crash during `tofu apply`

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

OpenTofu crashed! This is always indicative of a bug within OpenTofu.
Please report the crash with OpenTofu[1] so that we can fix this.

When reporting bugs, please include your OpenTofu version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/opentofu/opentofu/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

source and content cannot both be null
goroutine 156 [running]:
runtime/debug.Stack()
        /Users/arelrabinowitz/sdk/go1.21.4/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
        /Users/arelrabinowitz/sdk/go1.21.4/src/runtime/debug/stack.go:16 +0x1c
github.com/opentofu/opentofu/internal/logging.PanicHandler()
        /Users/arelrabinowitz/Projects/opentf/internal/logging/panic.go:58 +0x164
panic({0x104179f80?, 0x1047595c0?})
        /Users/arelrabinowitz/sdk/go1.21.4/src/runtime/panic.go:920 +0x254
github.com/opentofu/opentofu/internal/builtin/provisioners/file.getSrc({{{0x104794e08, 0x140004e6d60}}, {0x1042918e0, 0x1400082eea0}})
        /Users/arelrabinowitz/Projects/opentf/internal/builtin/provisioners/file/resource_provisioner.go:150 +0x328
github.com/opentofu/opentofu/internal/builtin/provisioners/file.(*provisioner).ProvisionResource(0x1400079d1a0, {{{{0x104794e08, 0x140004e6d60}}, {0x1042918e0, 0x1400082eea0}}, {{{0x104794e08, 0x140006525c0}}, {0x1042918e0, 0x1400082ef30}}, {0x10475fba0, ...}})
        /Users/arelrabinowitz/Projects/opentf/internal/builtin/provisioners/file/resource_provisioner.go:100 +0x330
github.com/opentofu/opentofu/internal/tofu.(*NodeAbstractResourceInstance).applyProvisioners(0x140001f8e00, {0x1047a59d8, 0x14000a6c1c0}, 0x1400093b5c0, 0x1, {0x1400093e290, 0x1, 0x1})
        /Users/arelrabinowitz/Projects/opentf/internal/tofu/node_resource_abstract_instance.go:2123 +0x103c
github.com/opentofu/opentofu/internal/tofu.(*NodeAbstractResourceInstance).evalApplyProvisioners(0x140001f8e00, {0x1047a59d8, 0x14000a6c1c0}, 0x1400093b5c0, 0x1, 0x1)
        /Users/arelrabinowitz/Projects/opentf/internal/tofu/node_resource_abstract_instance.go:1969 +0x430
github.com/opentofu/opentofu/internal/tofu.(*NodeApplyableResourceInstance).managedResourceExecute(0x14000aa4140, {0x1047a59d8, 0x14000a6c1c0})
        /Users/arelrabinowitz/Projects/opentf/internal/tofu/node_resource_apply_instance.go:332 +0x182c
github.com/opentofu/opentofu/internal/tofu.(*NodeApplyableResourceInstance).Execute(0x14000aa4140, {0x1047a59d8, 0x14000a6c1c0}, 0x1)
        /Users/arelrabinowitz/Projects/opentf/internal/tofu/node_resource_apply_instance.go:145 +0x134
github.com/opentofu/opentofu/internal/tofu.(*ContextGraphWalker).Execute(0x14000aeb680, {0x1047a59d8, 0x14000a6c1c0}, {0x12d80dc00, 0x14000aa4140})
        /Users/arelrabinowitz/Projects/opentf/internal/tofu/graph_walk_context.go:143 +0xd8
github.com/opentofu/opentofu/internal/tofu.(*Graph).walk.func1({0x104723040, 0x14000aa4140})
        /Users/arelrabinowitz/Projects/opentf/internal/tofu/graph.go:78 +0x3f4
github.com/opentofu/opentofu/internal/dag.(*Walker).walkVertex(0x14000a642a0, {0x104723040, 0x14000aa4140}, 0x14000aa50c0)
        /Users/arelrabinowitz/Projects/opentf/internal/dag/walk.go:384 +0x318
created by github.com/opentofu/opentofu/internal/dag.(*Walker).Update in goroutine 148
        /Users/arelrabinowitz/Projects/opentf/internal/dag/walk.go:307 +0xdb4
```

### Steps to Reproduce

1. `tofu init`.
2. `tofu apply`

### References

Related issue in the Terraform repository - https://github.com/hashicorp/terraform/issues/34454

**Comment by chenzejun** [comment]
@RLRabinowitz This looks interesting, may I take it?

**Comment by cam72cam** [comment]
Sure, thank you @chenzejun !
