### ISSUE TITLE
Crash when using a conditional with Twingate resource

### ISSUE THREAD

**Issue by RLRabinowitz** [opentofu/opentofu#1380]
### OpenTofu Version

```shell
1.6.2
```

### OpenTofu Configuration Files

```hcl
terraform {
  required_providers {
    twingate = {
      source  = "Twingate/twingate"
      version = "~> 2.0"
    }
  }
}

provider "twingate" {
  api_token = "redacted"
  network   = "redacted"
}

variable "tcp_port_list" {
  default = ["80", "443"]
}

resource "twingate_resource" "twingate" {
  name              = "example"
  address           = "example.com"
  remote_network_id = "redacted"

  protocols = {
    tcp = length(var.tcp_port_list) == 0 ? { policy = "ALLOW_ALL" } : { policy = "RESTRICTED", ports = var.tcp_port_list }
  }
}
```

### Debug Output

.

### Expected Behavior

Should not crash

### Actual Behavior

Crashed:
```
!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 47 [running]:
runtime/debug.Stack()
        /Users/arelrabinowitz/sdk/go1.21.4/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
        /Users/arelrabinowitz/sdk/go1.21.4/src/runtime/debug/stack.go:16 +0x1c
github.com/opentofu/opentofu/internal/logging.PanicHandler()
        /Users/arelrabinowitz/Projects/opentf/internal/logging/panic.go:60 +0x164
panic({0x1083ee880?, 0x109ead020?})
        /Users/arelrabinowitz/sdk/go1.21.4/src/runtime/panic.go:920 +0x254
github.com/zclconf/go-cty/cty.Type.FriendlyName({{0x0, 0x0}})
        /Users/arelrabinowitz/go/pkg/mod/github.com/zclconf/go-cty@v1.14.1/cty/type.go:47 +0x28
github.com/zclconf/go-cty/cty.testConformance({{0x0, 0x0}}, {{0x1088c28f0, 0x14000011671}}, {0x140009afc40, 0x4, 0x4}, 0x140009b7f80)
        /Users/arelrabinowitz/go/pkg/mod/github.com/zclconf/go-cty@v1.14.1/cty/type_conform.go:137 +0xa04
github.com/zclconf/go-cty/cty.testConformance({{0x1088c28b8, 0x1400098ee30}}, {{0x1088c28b8, 0x1400098f0b0}}, {0x140009afc40, 0x4, 0x4}, 0x140009b7f80)
        /Users/arelrabinowitz/go/pkg/mod/github.com/zclconf/go-cty@v1.14.1/cty/type_conform.go:130 +0x9bc
github.com/zclconf/go-cty/cty.testConformance({{0x1088c2928, 0x1400098ee40}}, {{0x1088c2928, 0x1400098f0c0}}, {0x140009afc40, 0x3, 0x4}, 0x140009b7f80)
        /Users/arelrabinowitz/go/pkg/mod/github.com/zclconf/go-cty@v1.14.1/cty/type_conform.go:76 +0x13a4
github.com/zclconf/go-cty/cty.testConformance({{0x1088c2928, 0x1400098efa0}}, {{0x1088c2928, 0x1400098f0f0}}, {0x1400076dcc0, 0x2, 0x2}, 0x140009b7f80)
        /Users/arelrabinowitz/go/pkg/mod/github.com/zclconf/go-cty@v1.14.1/cty/type_conform.go:76 +0x13a4
github.com/zclconf/go-cty/cty.testConformance({{0x1088c2928, 0x1400098f070}}, {{0x1088c2928, 0x1400098f140}}, {0x1400098f150, 0x1, 0x1}, 0x140009b7f80)
        /Users/arelrabinowitz/go/pkg/mod/github.com/zclconf/go-cty@v1.14.1/cty/type_conform.go:76 +0x13a4
github.com/zclconf/go-cty/cty.Type.TestConformance({{0x1088c2928, 0x1400098f070}}, {{0x1088c2928, 0x1400098f140}})
        /Users/arelrabinowitz/go/pkg/mod/github.com/zclconf/go-cty@v1.14.1/cty/type_conform.go:27 +0x78
github.com/zclconf/go-cty/cty/msgpack.Marshal({{{0x1088c2928, 0x1400098f070}}, {0x1083bdee0, 0x14000875ef0}}, {{0x1088c2928, 0x1400098f140}})
        /Users/arelrabinowitz/go/pkg/mod/github.com/zclconf/go-cty@v1.14.1/cty/msgpack/marshal.go:19 +0x6c
github.com/opentofu/opentofu/internal/plugin6.(*GRPCProvider).ValidateResourceConfig(0x14000a12600, {{0x14000052630, 0x11}, {{{0x1088c2928, 0x1400098f070}}, {0x1083bdee0, 0x14000875ef0}}})
        /Users/arelrabinowitz/Projects/opentf/internal/plugin6/grpc_provider.go:218 +0x1b0
github.com/opentofu/opentofu/internal/tofu.(*NodeValidatableResource).validateResource(0x14000a10038, {0x1088d3a70, 0x1400081e0f0})
        /Users/arelrabinowitz/Projects/opentf/internal/tofu/node_resource_validate.go:429 +0x19b0
github.com/opentofu/opentofu/internal/tofu.(*NodeValidatableResource).Execute(0x14000a10038, {0x1088d3a70, 0x1400081e0f0}, 0x4)
        /Users/arelrabinowitz/Projects/opentf/internal/tofu/node_resource_validate.go:54 +0x64
github.com/opentofu/opentofu/internal/tofu.(*ContextGraphWalker).Execute(0x14000a0fd40, {0x1088d3a70, 0x1400081e0f0}, {0x15199d490, 0x14000a10038})
        /Users/arelrabinowitz/Projects/opentf/internal/tofu/graph_walk_context.go:146 +0xd8
github.com/opentofu/opentofu/internal/tofu.(*Graph).walk.func1({0x1087e0920, 0x14000a10038})
        /Users/arelrabinowitz/Projects/opentf/internal/tofu/graph.go:80 +0x3f4
github.com/opentofu/opentofu/internal/dag.(*Walker).walkVertex(0x14000d88780, {0x1087e0920, 0x14000a10038}, 0x14000720700)
        /Users/arelrabinowitz/Projects/opentf/internal/dag/walk.go:386 +0x318
created by github.com/opentofu/opentofu/internal/dag.(*Walker).Update in goroutine 37
        /Users/arelrabinowitz/Projects/opentf/internal/dag/walk.go:309 +0xdb4
```

### Steps to Reproduce

1. `tofu init`
2. `tofu plan`

### References

Related issue in the Terraform repository - https://github.com/hashicorp/terraform/issues/34540

**Comment by namgyalangmo** [comment]
I would like to resolve this!

**Comment by cam72cam** [comment]
Thanks @namgyalangmo, I've assigned it to you

**Comment by ollevche** [comment]
Hey @namgyalangmo! Thanks for the clarification and debugging!

We certainly don't want `tofu` to randomly crash, errors must be gracefully handled. In this case, we want to have a clear error message stating what's exactly wrong with the configuration.

I also looked at the issue quickly, and it seems like the underlying `go-cty` implementation causes panic.

It was already fixed in https://github.com/zclconf/go-cty/pull/175 and we need to update the dependency.
