### ISSUE TITLE
[State Encryption] getting panic on apply with remote backend

### ISSUE THREAD

**Issue by ollevche** [opentofu/opentofu#1426]
### Did you test the state encryption?

Tested, did not work / had problems

### Additional feedback / details on the state encryption

Hey there!

Did a very basic encryption test with Scalr remote backend and a single `null_resource`.

Getting a panic when `tofu` tries to write an encrypted state.

Given the following `main.tf`:

```hcl
terraform {
  backend "remote" {
    hostname = "YOUR_VALUE"
    organization = "YOUR_VALUE"

    workspaces {
      name = "YOUR_VALUE"
    }
  }

  encryption {
    key_provider "pbkdf2" "my_passphrase" {
      passphrase = "Be`v`360BI~HP5s;"
    }

    method "aes_gcm" "my_method" {
      keys = key_provider.pbkdf2.my_passphrase
    }

    state {
      method = method.aes_gcm.my_method
    }
  }
}

resource "null_resource" "example" {
  provisioner "local-exec" {
    command = "echo 'Congrats on your first run!'"
   }
}

```

I'm getting the following panic trace an `apply` (`plan` has no issues):

<details><summary>Log</summary>
<p>

!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

OpenTofu crashed! This is always indicative of a bug within OpenTofu.
Please report the crash with OpenTofu[1] so that we can fix this.

When reporting bugs, please include your OpenTofu version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/opentofu/opentofu/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 73 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x13
github.com/opentofu/opentofu/internal/logging.PanicHandlerWithTrace({0xc00024f800, 0x48b, 0x800})
        /Users/ollevche/Projects/opentofu/internal/logging/panic.go:64 +0x154
panic({0x2ddd480?, 0x53f10e0?})
        /usr/local/go/src/runtime/panic.go:770 +0x132
github.com/opentofu/opentofu/internal/states/statefile.writeStateV4(0xc000e42090, {0x3afe220, 0xc00092a6b8}, {0x0, 0x0})
        /Users/ollevche/Projects/opentofu/internal/states/statefile/version4.go:439 +0xa34
github.com/opentofu/opentofu/internal/states/statefile.Write(0xc00011e900?, {0x3afe220?, 0xc00092a6b8?}, {0x0?, 0x0?})
        /Users/ollevche/Projects/opentofu/internal/states/statefile/write.go:21 +0x4b
github.com/opentofu/opentofu/internal/states/statemgr.(*Filesystem).persistState(0xc000e24480, 0xc000c2c390?)
        /Users/ollevche/Projects/opentofu/internal/states/statemgr/filesystem.go:239 +0x95c
github.com/opentofu/opentofu/internal/states/statemgr.(*Filesystem).WriteStateForMigration(0xc000e24480, 0xc000e39e90, 0x1)
        /Users/ollevche/Projects/opentofu/internal/states/statemgr/filesystem.go:474 +0x46a
github.com/opentofu/opentofu/internal/backend/local.(*Local).backupStateForError(0xc000677340, 0xc000e39e90, {0x3afef20?, 0xc000c69060?}, {0x3b45a40, 0xc000a02690})
        /Users/ollevche/Projects/opentofu/internal/backend/local/backend_apply.go:299 +0x1d3
github.com/opentofu/opentofu/internal/backend/local.(*Local).opApply(0xc000677340, {0x3b38dd0, 0xc0007210e0}, {0x3b38dd0, 0xc000721130}, 0xc00029b180, 0xc000432600)
        /Users/ollevche/Projects/opentofu/internal/backend/local/backend_apply.go:268 +0x156e
github.com/opentofu/opentofu/internal/backend/local.(*Local).Operation.func1()
        /Users/ollevche/Projects/opentofu/internal/backend/local/backend.go:340 +0x12d
created by github.com/opentofu/opentofu/internal/backend/local.(*Local).Operation in goroutine 1
        /Users/ollevche/Projects/opentofu/internal/backend/local/backend.go:333 +0x452
With go-routine called from:
goroutine 1 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/opentofu/opentofu/internal/backend/local.(*Local).Operation(0xc000677340, {0x3b38d28, 0x550a280}, 0xc00029b180)
        /Users/ollevche/Projects/opentofu/internal/backend/local/backend.go:330 +0x31f
github.com/opentofu/opentofu/internal/backend/remote.(*Remote).Operation(0xc0002a5a40, {0x3b38d28, 0x550a280}, 0xc00029b180)
        /Users/ollevche/Projects/opentofu/internal/backend/remote/backend.go:782 +0x19f
github.com/opentofu/opentofu/internal/command.(*Meta).RunOperation(0xc0002c4fc0, {0x7c408cf8f6a8?, 0xc0002a5a40?}, 0xc00029b180)
        /Users/ollevche/Projects/opentofu/internal/command/meta.go:480 +0xbd
github.com/opentofu/opentofu/internal/command.(*ApplyCommand).Run(0xc0002c4fc0, {0xc000140020, 0x5, 0x5})
        /Users/ollevche/Projects/opentofu/internal/command/apply.go:135 +0xb28
github.com/mitchellh/cli.(*CLI).Run(0xc00080fb80)
        /Users/ollevche/go/pkg/mod/github.com/mitchellh/cli@v1.1.5/cli.go:262 +0x5b8
main.realMain()
        /Users/ollevche/Projects/opentofu/cmd/tofu/main.go:347 +0x202b
main.main()
        /Users/ollevche/Projects/opentofu/cmd/tofu/main.go:66 +0x13

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Apply operation failed

Error: "errored.tfstate" could not be decoded. input length is 0: line 1 column 1 (char 0)

</p>
</details>

Please, note that my build contains a recent improvement for panic traces: https://github.com/opentofu/opentofu/pull/1425

### Did you test the removed block?

Did not test

### Did you test the testing feature changes?

Did not test

### Did you test the built-in functions?

Did not test

### Did you test the CLI changes?

Did not test

**Comment by ollevche** [comment]
After an internal discussion with @janosdebugs @Yantrio and @cam72cam seems like the bug is [hidden here](https://github.com/opentofu/opentofu/blob/main/internal/backend/remote/backend.go#L381). I'll prepare a PR with fix and double test it.
