### ISSUE TITLE
Panic on sensitive template values

### ISSUE THREAD

**Issue by cam72cam** [opentofu/opentofu#1798]
### OpenTofu Version

```shell
1.7.3
```

### OpenTofu Configuration Files

```hcl
locals {
        x = templatefile(sensitive("my.tmpl"), {})
}
```

### Debug Output

N/A

### Expected Behavior

Template output should be sensitive

### Actual Behavior

```go
 Call to function "templatefile" failed: panic in function implementation: value is marked, so must be unmarked first
│ goroutine 85 [running]:
│ runtime/debug.Stack()
│       /usr/lib/go-1.22/src/runtime/debug/stack.go:24 +0x5e
│ github.com/zclconf/go-cty/cty/function.errorForPanic(...)
│       /home/cmesh/go/pkg/mod/github.com/zclconf/go-cty@v1.14.4/cty/function/error.go:44
│ github.com/zclconf/go-cty/cty/function.Function.returnTypeForValues.func1()
│       /home/cmesh/go/pkg/mod/github.com/zclconf/go-cty@v1.14.4/cty/function/function.go:226 +0x7b
│ panic({0x2cfc300?, 0x3b81310?})
│       /usr/lib/go-1.22/src/runtime/panic.go:770 +0x132
│ github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
│       /home/cmesh/go/pkg/mod/github.com/zclconf/go-cty@v1.14.4/cty/marks.go:141
│ github.com/zclconf/go-cty/cty.Value.AsString({{{0x3bc0818?, 0xc000132fa1?}}, {0x2fa2f40?, 0xc00098cb58?}})
│       /home/cmesh/go/pkg/mod/github.com/zclconf/go-cty@v1.14.4/cty/value_ops.go:1385 +0x47
│ github.com/opentofu/opentofu/internal/lang/funcs.makeTemplateFileFuncImpl.func1({0xc0009a6d50, 0x8}, 0xc0007b3868)
│       /home/cmesh/OpenTOFU/opentofu-community/internal/lang/funcs/filesystem.go:154 +0x110
│ github.com/opentofu/opentofu/internal/lang/funcs.makeTemplateFileFuncImpl.func3({0xc0008d4180, 0x2, 0x3bc0cb0?})
│       /home/cmesh/OpenTOFU/opentofu-community/internal/lang/funcs/filesystem.go:188 +0x1fe
│ github.com/zclconf/go-cty/cty/function.Function.returnTypeForValues({0x10?}, {0xc0008d4180, 0x2, 0x3bc09d8?})
│       /home/cmesh/go/pkg/mod/github.com/zclconf/go-cty@v1.14.4/cty/function/function.go:230 +0x79b
│ github.com/zclconf/go-cty/cty/function.Function.Call({0x3bc09d8?}, {0xc0008d4180, 0x2, 0x2})
│       /home/cmesh/go/pkg/mod/github.com/zclconf/go-cty@v1.14.4/cty/function/function.go:250 +0x7a
│ github.com/hashicorp/hcl/v2/hclsyntax.(*FunctionCallExpr).Value(0xc0009dc0f0, 0xc00098c7e0)
│       /home/cmesh/go/pkg/mod/github.com/opentofu/hcl/v2@v2.0.0-20240416130056-03228b26f391/hclsyntax/expression.go:528 +0x1aef
│ github.com/opentofu/opentofu/internal/lang.(*Scope).EvalExpr(0xc0000f4a20, {0x3bc0f98, 0xc0009dc0f0}, {{0x3bc0cb0?, 0x55aa6e0?}})
│       /home/cmesh/OpenTOFU/opentofu-community/internal/lang/eval.go:182 +0x1c2
│ github.com/opentofu/opentofu/internal/tofu.(*BuiltinEvalContext).EvaluateExpr(0x34d2ab0?, {0x3bc0f98, 0xc0009dc0f0}, {{0x3bc0cb0?, 0x55aa6e0?}}, {0x0?, 0x0?})
│       /home/cmesh/OpenTOFU/opentofu-community/internal/tofu/eval_context_builtin.go:295 +0xab
│ github.com/opentofu/opentofu/internal/tofu.(*NodeLocal).Execute(0x10?, {0x3be1978, 0xc0001d9500}, 0x80?)
│       /home/cmesh/OpenTOFU/opentofu-community/internal/tofu/node_local.go:160 +0x5e4
│ github.com/opentofu/opentofu/internal/tofu.(*ContextGraphWalker).Execute(0xc0009de900, {0x3be1978, 0xc0001d9500}, {0x7f31ab2a1bd0, 0xc0009e18c0})
│       /home/cmesh/OpenTOFU/opentofu-community/internal/tofu/graph_walk_context.go:147 +0xbb
│ github.com/opentofu/opentofu/internal/tofu.(*Graph).walk.func1({0x30e2d60, 0xc0009e18c0})
│       /home/cmesh/OpenTOFU/opentofu-community/internal/tofu/graph.go:86 +0x3f2
│ github.com/opentofu/opentofu/internal/dag.(*Walker).walkVertex(0xc00098a600, {0x30e2d60, 0xc0009e18c0}, 0xc0009a04c0)
│       /home/cmesh/OpenTOFU/opentofu-community/internal/dag/walk.go:385 +0x2d7
│ created by github.com/opentofu/opentofu/internal/dag.(*Walker).Update in goroutine 83
│       /home/cmesh/OpenTOFU/opentofu-community/internal/dag/walk.go:308 +0xff3
```

### Steps to Reproduce

tofu init
tofu plan

### Additional Context

We should also confirm that this works as expected with `templatestring`

### References

- Do not look at PR linked to https://github.com/hashicorp/terraform/issues/31119 if working on this issue

**Comment by cam72cam** [comment]
Some credentials file with a sensitive ID in the name?
