### ISSUE TITLE
`tofu init` crashes for modules without source

### ISSUE THREAD

**Issue by sugar700** [opentofu/opentofu#1887]
### OpenTofu Version

```shell
OpenTofu v1.8.0
on linux_amd64
```

### OpenTofu Configuration Files

`main.tf`:

```hcl
module "example" {}
```

### Debug Output

```
Initializing the backend...
Initializing modules...

!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

OpenTofu crashed! This is always indicative of a bug within OpenTofu.
Please report the crash with OpenTofu[1] so that we can fix this.

When reporting bugs, please include your OpenTofu version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/opentofu/opentofu/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
        runtime/debug/stack.go:16 +0x13
github.com/opentofu/opentofu/internal/logging.panicHandler({0x2e52c00, 0x54766c0}, {0x0, 0x0, 0x0})
        github.com/opentofu/opentofu/internal/logging/panic.go:96 +0xe5
github.com/opentofu/opentofu/internal/logging.PanicHandler()
        github.com/opentofu/opentofu/internal/logging/panic.go:51 +0x88
panic({0x2e52c00?, 0x54766c0?})
        runtime/panic.go:770 +0x132
github.com/opentofu/opentofu/internal/configs.buildChildModules(0xc00011e540, {0x3b8dce0, 0xc0005e05f0})
        github.com/opentofu/opentofu/internal/configs/config_build.go:141 +0x31d
github.com/opentofu/opentofu/internal/configs.BuildConfig(0xc000126600, {0x3b8dce0, 0xc0005e05f0})
        github.com/opentofu/opentofu/internal/configs/config_build.go:33 +0x75
github.com/opentofu/opentofu/internal/initwd.(*ModuleInstaller).installDescendentModules(0xc00060cbd0, 0xc000126600, 0xc00060d1d0, {0x3b8dce0, 0xc0005e05f0}, 0x0)
        github.com/opentofu/opentofu/internal/initwd/module_install.go:316 +0x105
github.com/opentofu/opentofu/internal/initwd.(*ModuleInstaller).InstallModules(0xc00060cbd0, {0x3bc49b0, 0xc00060cab0}, {0x3b7b520, 0x1}, {0x331398f, 0x5}, 0x0, 0x0, {0x3b9b900, ...}, ...)
        github.com/opentofu/opentofu/internal/initwd/module_install.go:141 +0x69c
github.com/opentofu/opentofu/internal/command.(*Meta).installModules(0xc0005e34a0, {0x3bc49b0?, 0xc00060ca80?}, {0xc000082024, 0x1c}, {0x331398f, 0x5}, 0x0, 0x0, {0x3b9b900, ...})
        github.com/opentofu/opentofu/internal/command/meta_config.go:275 +0x632
github.com/opentofu/opentofu/internal/command.(*InitCommand).getModules(0xc0005e34a0, {0x3bc49e8, 0xc0005e00f0}, {0xc000082024, 0x1c}, {0x331398f, 0x5}, 0xc000126400, 0x0)
        github.com/opentofu/opentofu/internal/command/init.go:421 +0x73c
github.com/opentofu/opentofu/internal/command.(*InitCommand).Run(0xc0005e34a0, {0xc0001bc010, 0x0, 0x0})
        github.com/opentofu/opentofu/internal/command/init.go:268 +0x1cf1
github.com/mitchellh/cli.(*CLI).Run(0xc0007ba280)
        github.com/mitchellh/cli@v1.1.5/cli.go:262 +0x5b8
main.realMain()
        github.com/opentofu/opentofu/cmd/tofu/main.go:347 +0x202b
main.main()
        github.com/opentofu/opentofu/cmd/tofu/main.go:66 +0x13

```

### Expected Behavior

OpenTofu should report an error without crashing.

### Actual Behavior

OpenTofu crashes.

### Steps to Reproduce

1. Create `main.tf` file with following contents:
  ```hcl
  module "example" {}
  ```
2. Run `tofu init`.

**Comment by cam72cam** [comment]
Thanks for the report, taking a look!

**Comment by cam72cam** [comment]
This will be out in v1.8.1, we don't have a firm date on that patch release yet.
