### ISSUE TITLE
OpenTofu Crash during tofu plan Command with AWS Elasticache Import

### ISSUE THREAD

**Issue by atsushi-ambo** [opentofu/opentofu#1984]
### OpenTofu Version

```shell
OpenTofu v1.8.2
on linux_amd64
```

### OpenTofu Configuration Files

```hcl
...tofu config...
```

### Debug Output

```
stg % tofu plan -generate-config-out=generated_resources.tf
aws_elasticache_replication_group.XXX_redis: Preparing import... [id=XXX-redis]
aws_elasticache_replication_group.XXX_redis: Refreshing state... [id=XXX-redis]

!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

OpenTofu crashed! This is always indicative of a bug within OpenTofu.
Please report the crash with OpenTofu[1] so that we can fix this.

When reporting bugs, please include your OpenTofu version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/opentofu/opentofu/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

value is marked, so must be unmarked first
goroutine 121 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
        runtime/debug/stack.go:16 +0x1c
github.com/opentofu/opentofu/internal/logging.panicHandler({0x105858440, 0x105e7a190}, {0x14001940800, 0x365, 0x400})
        github.com/opentofu/opentofu/internal/logging/panic.go:96 +0xcc
github.com/opentofu/opentofu/internal/tofu.(*Graph).walk.PanicHandlerWithTraceFn.func2()
        github.com/opentofu/opentofu/internal/logging/panic.go:82 +0x8c
panic({0x105858440?, 0x105e7a190?})
        runtime/panic.go:920 +0x26c
github.com/zclconf/go-cty/cty.Value.assertUnmarked(...)
        github.com/zclconf/go-cty@v1.14.4/cty/marks.go:141
github.com/zclconf/go-cty/cty.Value.AsString({{{0x105eb8e18?, 0x1400000f031?}}, {0x105b038e0?, 0x14003780fc0?}})
        github.com/zclconf/go-cty@v1.14.4/cty/value_ops.go:1385 +0x54
github.com/opentofu/opentofu/internal/genconfig.writeConfigAttributesFromExisting({{}, {0x10771fb20, 0x0, 0x0}, {{}, {{}, 0x4d, {0x1400056e720, 0x21}, {0x1400080ac50, ...}}, ...}}, ...)
        github.com/opentofu/opentofu/internal/genconfig/generate_config.go:158 +0x5a8
github.com/opentofu/opentofu/internal/genconfig.GenerateResourceContents({{}, {0x10771fb20, 0x0, 0x0}, {{}, {{}, 0x4d, {0x1400056e720, 0x21}, {0x1400080ac50, ...}}, ...}}, ...)
        github.com/opentofu/opentofu/internal/genconfig/generate_config.go:48 +0x510
github.com/opentofu/opentofu/internal/tofu.(*NodePlannableResourceInstance).generateHCLStringAttributes(0x1400192b4a0, {{}, {0x10771fb20, 0x0, 0x0}, {{}, {{}, 0x4d, {0x1400056e720, 0x21}, ...}, ...}}, ...)
        github.com/opentofu/opentofu/internal/tofu/node_resource_plan_instance.go:682 +0x154
github.com/opentofu/opentofu/internal/tofu.(*NodePlannableResourceInstance).importState(0x1400192b4a0, {0x105ed3ca0, 0x140017cc500}, {{}, {0x10771fb20, 0x0, 0x0}, {{}, {{}, 0x4d, ...}, ...}}, ...)
        github.com/opentofu/opentofu/internal/tofu/node_resource_plan_instance.go:607 +0x1090
github.com/opentofu/opentofu/internal/tofu.(*NodePlannableResourceInstance).managedResourceExecute(0x1400192b4a0, {0x105ed3ca0, 0x140017cc500})
        github.com/opentofu/opentofu/internal/tofu/node_resource_plan_instance.go:203 +0x590
github.com/opentofu/opentofu/internal/tofu.(*NodePlannableResourceInstance).Execute(0x12d1fcc68?, {0x105ed3ca0?, 0x140017cc500?}, 0x80?)
        github.com/opentofu/opentofu/internal/tofu/node_resource_plan_instance.go:92 +0x7c
github.com/opentofu/opentofu/internal/tofu.(*ContextGraphWalker).Execute(0x140077a7c20, {0x105ed3ca0, 0x140017cc500}, {0x156f20e38, 0x1400192b4a0})
        github.com/opentofu/opentofu/internal/tofu/graph_walk_context.go:147 +0xa0
github.com/opentofu/opentofu/internal/tofu.(*Graph).walk.func1({0x105e34460, 0x1400192b4a0})
        github.com/opentofu/opentofu/internal/tofu/graph.go:86 +0x27c
github.com/opentofu/opentofu/internal/dag.(*Walker).walkVertex(0x14000a4a840, {0x105e34460, 0x1400192b4a0}, 0x14001905600)
        github.com/opentofu/opentofu/internal/dag/walk.go:385 +0x2a8
created by github.com/opentofu/opentofu/internal/dag.(*Walker).Update in goroutine 271
        github.com/opentofu/opentofu/internal/dag/walk.go:308 +0xb0c
With go-routine called from:
goroutine 271 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x64
github.com/opentofu/opentofu/internal/logging.PanicHandlerWithTraceFn(...)
        github.com/opentofu/opentofu/internal/logging/panic.go:72
github.com/opentofu/opentofu/internal/tofu.(*Graph).walk(0x14001aa6240, {0x105eb9788, 0x140077a7c20})
        github.com/opentofu/opentofu/internal/tofu/graph.go:51 +0x40
github.com/opentofu/opentofu/internal/tofu.(*Graph).walk.func1({0x105dce120, 0x14001b6c460})
        github.com/opentofu/opentofu/internal/tofu/graph.go:127 +0x5f8
github.com/opentofu/opentofu/internal/dag.(*Walker).walkVertex(0x14000926ba0, {0x105dce120, 0x14001b6c460}, 0x14001ebda40)
        github.com/opentofu/opentofu/internal/dag/walk.go:385 +0x2a8
created by github.com/opentofu/opentofu/internal/dag.(*Walker).Update in goroutine 209
        github.com/opentofu/opentofu/internal/dag/walk.go:308 +0xb0c
```

### Expected Behavior

The tofu plan command should execute successfully without crashing.

### Actual Behavior

OpenTofu crashes and outputs a stack trace.

### Steps to Reproduce

1. Set up an import configuration in import.tf:
```
import {
  to = aws_elasticache_replication_group.XXX_redis
  id = "XXX-redis"
}
```
2. Execute the command:
```
tofu plan -generate-config-out=generated_resources.tf
```
3. Witnessed a crash with the following error message.

**Comment by Evi1Pumpkin** [comment]
Hello and thank you for this issue! The core team regularly reviews new issues and discusses them, but this can take a little time. Please bear with us while we get to your issue. If you're interested, the contribution guide has a section about the [decision-making process](https://github.com/opentofu/opentofu/blob/main/CONTRIBUTING.md#who-decides-if-a-feature-will-be-implemented-and-how-is-that-decision-made).

**Comment by ollevche** [comment]
Hey @atsushi-ambo, thanks for reporting the issue!

I reproduced the crash with the same `aws_elasticache_replication_group`. It is fixed in #1986 and waiting to be merged and released.

However, the resulting configuration should be manually tweaked due to conflicting default values. We have another issue for that case - https://github.com/opentofu/opentofu/issues/1592. If you have any relevant input - feel free to share.

**Comment by atsushi-ambo** [comment]
@ollevche 
Thanks for the update! I'm looking forward to the release. I'll look for any relevant input regarding the generate-config-out flag issue and share it if I find any.
