### ISSUE TITLE
#300: Crash on dynamically indexed provider

### ISSUE THREAD

**Issue by ghost** [opentofu/opentofu#2101]
Related to: #2089, #2088
Main PR: #2054

When using the following code on the `300_static_evaluate_provider_mappings_alias_vs_instance` branch OpenTofu crashes:

```hcl2
terraform {
  required_providers {
    d = {
      source = "kreuzwerker/docker"
      version = "3.0.2"
    }
  }
}

locals {
  addrs = [
    "127.0.0.1:1",
    "127.0.0.1:2",
    "127.0.0.1:3",
    "unix:///var/run/docker.sock"
  ]
}

provider "d" {
  host     = each.value
  for_each = local.addrs
}

resource "docker_image" "ubuntu" {
  provider = d[3]
  name     = "ubuntu:latest"
}
```

<details>
<summary>Crash log</summary>

```
$ ../opentofu/tofu init

!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

OpenTofu crashed! This is always indicative of a bug within OpenTofu.
Please report the crash with OpenTofu[1] so that we can fix this.

When reporting bugs, please include your OpenTofu version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/opentofu/opentofu/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

not a string
goroutine 1 [running]:
runtime/debug.Stack()
        ~/sdk/go1.23.1/src/runtime/debug/stack.go:26 +0x5e
runtime/debug.PrintStack()
        ~/sdk/go1.23.1/src/runtime/debug/stack.go:18 +0x13
github.com/opentofu/opentofu/internal/logging.panicHandler({0x2d309a0, 0x3994220}, {0x0, 0x0, 0x0})
        ~/opentofu/internal/logging/panic.go:96 +0xd6
github.com/opentofu/opentofu/internal/logging.PanicHandler()
        ~/opentofu/internal/logging/panic.go:51 +0x85
panic({0x2d309a0?, 0x3994220?})
        ~/sdk/go1.23.1/src/runtime/panic.go:785 +0x132
github.com/zclconf/go-cty/cty.Value.AsString({{{0x39d4910?, 0xc000124e10?}}, {0x3324480?, 0xc000938120?}})
        ~/go/pkg/mod/github.com/zclconf/go-cty@v1.14.4/cty/value_ops.go:1387 +0x11e
github.com/opentofu/opentofu/internal/configs.decodeProviderConfigRef({0x39d51a8?, 0xc00093cf60?}, {0x335a3c8, 0x8})
        ~/opentofu/internal/configs/resource.go:1059 +0xa78
github.com/opentofu/opentofu/internal/configs.decodeProviderConfigRefMapping({0x39d51a8?, 0xc00093cf60?}, {0x335a3c8?, 0x8?})
        ~/opentofu/internal/configs/resource.go:987 +0x49
github.com/opentofu/opentofu/internal/configs.decodeResourceBlock(0xc00092d860, 0x0)
        ~/opentofu/internal/configs/resource.go:206 +0x785
github.com/opentofu/opentofu/internal/configs.(*Parser).loadConfigFile(0xc0005b53e0, {0xc00034ebd0?, 0x3353cdb?}, 0x0)
        ~/opentofu/internal/configs/parser_config.go:173 +0x1427
github.com/opentofu/opentofu/internal/configs.(*Parser).LoadConfigFile(...)
        ~/opentofu/internal/configs/parser_config.go:28
github.com/opentofu/opentofu/internal/configs.(*Parser).loadFiles(0xc0005b53e0, {0xc0001a3f40?, 0x0?, 0xc0005b53e0?}, 0x0)
        ~/opentofu/internal/configs/parser_config_dir.go:130 +0xec
github.com/opentofu/opentofu/internal/configs.(*Parser).LoadConfigDirWithTests(0xc0005b53e0, {0x39896e0, 0x1}, {0x3353cdb?, 0x0?}, {{0x0, 0x0, 0x0}, 0xc000013cc8, {0x39896e0, ...}, ...})
        ~/opentofu/internal/configs/parser_config_dir.go:82 +0xe8
github.com/opentofu/opentofu/internal/command.(*Meta).loadSingleModuleWithTests(0xc000921680, {0xc00007a004?, 0xc00080e270?}, {0x3353cdb, 0x5})    
        ~/opentofu/internal/command/meta_config.go:198 +0x2a5
github.com/opentofu/opentofu/internal/command.(*InitCommand).Run(0xc000921680, {0xc0001c4010, 0x0, 0x0})
        ~/opentofu/internal/command/init.go:193 +0x13da
github.com/mitchellh/cli.(*CLI).Run(0xc00051a280)
        ~/go/pkg/mod/github.com/mitchellh/cli@v1.1.5/cli.go:262 +0x55f
main.realMain()
        ~/opentofu/cmd/tofu/main.go:347 +0x1fcb
main.main()
        ~/opentofu/cmd/tofu/main.go:66 +0x13
```

</details>

**Comment by ollevche** [comment]
I pushed a small fix for this issue for "the previous UX version" - https://github.com/opentofu/opentofu/pull/2054/commits/93c34d9eec4be0714ad0e947c694fa171884b346. It should be reflected in the new one (https://github.com/opentofu/opentofu/pull/2089) and potentially extended to support `count` keys.
