### ISSUE TITLE
Panic during backend/remote tests, possible race condition

### ISSUE THREAD

**Issue by cam72cam** [opentofu/opentofu#847]
### OpenTofu Version

```shell
1.6.0-dev (e2d5a17e564ea4f8ddd220d949d2361c625cc243)
```

### OpenTofu Configuration Files

N/A

### Debug Output

N/A

### Expected Behavior

Tests do not panic

### Actual Behavior

https://github.com/opentofu/opentofu/actions/runs/6814733024/job/18532269760

```
!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!
OpenTofu crashed! This is always indicative of a bug within OpenTofu.
Please report the crash with OpenTofu[1] so that we can fix this.

When reporting bugs, please include your OpenTofu version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/opentofu/opentofu/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
goroutine 64 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/debug/stack.go:16 +0x13
github.com/opentofu/opentofu/internal/logging.PanicHandler()
	/home/runner/work/opentofu/opentofu/internal/logging/panic.go:58 +0x13b
panic({0x1399280?, 0x239a6c0?})
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/panic.go:920 +0x270
github.com/opentofu/opentofu/internal/backend/remote.(*Remote).cancel(0xc0006360b0, {0x19bc5e8, 0xc00064af00}, 0xc000629560, 0xc0006924e0)
	/home/runner/work/opentofu/opentofu/internal/backend/remote/backend.go:877 +0xe1
github.com/opentofu/opentofu/internal/backend/remote.(*Remote).Operation.func1()
	/home/runner/work/opentofu/opentofu/internal/backend/remote/backend.go:854 +0x3b1
created by github.com/opentofu/opentofu/internal/backend/remote.(*Remote).Operation in goroutine 50
	/home/runner/work/opentofu/opentofu/internal/backend/remote/backend.go:819 +0x545
FAIL	github.com/opentofu/opentofu/internal/backend/remote	0.030s
```

### Steps to Reproduce

`go test ./internal/backend/remote/...`

**Comment by cam72cam** [comment]
I've got a better stack trace now from TestRemote_applyCanceled:
```
 runtime error: invalid memory address or nil pointer dereference
goroutine 30 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/debug/stack.go:16 +0x1c
github.com/opentofu/opentofu/internal/logging.panicHandler({0x114dda0, 0x2412a30}, {0x4000748000, 0x36d, 0x400})
	/home/runner/work/opentofu/opentofu/internal/logging/panic.go:96 +0xcc
github.com/opentofu/opentofu/internal/backend/remote.(*Remote).Operation.PanicHandlerWithTraceFn.func3()
	/home/runner/work/opentofu/opentofu/internal/logging/panic.go:82 +0x8c
panic({0x114dda0?, 0x2412a30?})
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/panic.go:920 +0x26c
github.com/opentofu/opentofu/internal/backend/remote.(*Remote).cancel(0x40001cb200, {0x1862478, 0x4000746140}, 0x4000510f00, 0x4000752340)
	/home/runner/work/opentofu/opentofu/internal/backend/remote/backend.go:888 +0xd0
github.com/opentofu/opentofu/internal/backend/remote.(*Remote).Operation.func1()
	/home/runner/work/opentofu/opentofu/internal/backend/remote/backend.go:865 +0x2d8
created by github.com/opentofu/opentofu/internal/backend/remote.(*Remote).Operation in goroutine 57
	/home/runner/work/opentofu/opentofu/internal/backend/remote/backend.go:830 +0x528
With go-routine called from:
goroutine 57 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/debug/stack.go:24 +0x64
github.com/opentofu/opentofu/internal/logging.PanicHandlerWithTraceFn(...)
	/home/runner/work/opentofu/opentofu/internal/logging/panic.go:72
github.com/opentofu/opentofu/internal/backend/remote.(*Remote).Operation(0x40001cb200, {0x1862280, 0x24905c0}, 0x4000510f00)
	/home/runner/work/opentofu/opentofu/internal/backend/remote/backend.go:827 +0x3b4
github.com/opentofu/opentofu/internal/backend/remote.TestRemote_applyCanceled(0x4000103860)
	/home/runner/work/opentofu/opentofu/internal/backend/remote/backend_apply_test.go:131 +0xdc
testing.tRunner(0x4000103860, 0x145cc20)
	/opt/hostedtoolcache/go/1.21.3/x64/src/testing/testing.go:1595 +0xe8
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.21.3/x64/src/testing/testing.go:1648 +0x33c
	```

**Comment by ollevche** [comment]
Here are more examples that potentially have the same root cause.

TestRemote_planCanceled test:
```
!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

OpenTofu crashed! This is always indicative of a bug within OpenTofu.
Please report the crash with OpenTofu[1] so that we can fix this.

When reporting bugs, please include your OpenTofu version, the stack trace
shown below, and any additional information which may help replicate the issue.

[1]: https://github.com/opentofu/opentofu/issues

!!!!!!!!!!!!!!!!!!!!!!!!!!! OPENTOFU CRASH !!!!!!!!!!!!!!!!!!!!!!!!!!!!

runtime error: invalid memory address or nil pointer dereference
--- FAIL: TestRemote_planCanceled (0.02s)
    backend_plan_test.go:126: expected plan operation to fail
goroutine 992 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/debug/stack.go:16 +0x1c
github.com/opentofu/opentofu/internal/logging.panicHandler({0x114e480, 0x2412a30}, {0x400053c000, 0x36c, 0x400})
	/home/runner/work/opentofu/opentofu/internal/logging/panic.go:96 +0xcc
github.com/opentofu/opentofu/internal/backend/remote.(*Remote).Operation.PanicHandlerWithTraceFn.func3()
	/home/runner/work/opentofu/opentofu/internal/logging/panic.go:82 +0x8c
panic({0x114e480?, 0x2412a30?})
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/panic.go:920 +0x26c
github.com/opentofu/opentofu/internal/backend/remote.(*Remote).cancel(0x4000923800, {0x1864738, 0x4000b57d10}, 0x40004dda40, 0x40004c6340)
	/home/runner/work/opentofu/opentofu/internal/backend/remote/backend.go:888 +0xd0
github.com/opentofu/opentofu/internal/backend/remote.(*Remote).Operation.func1()
	/home/runner/work/opentofu/opentofu/internal/backend/remote/backend.go:865 +0x2d8
created by github.com/opentofu/opentofu/internal/backend/remote.(*Remote).Operation in goroutine 938
	/home/runner/work/opentofu/opentofu/internal/backend/remote/backend.go:830 +0x528
With go-routine called from:
goroutine 938 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/debug/stack.go:24 +0x64
github.com/opentofu/opentofu/internal/logging.PanicHandlerWithTraceFn(...)
	/home/runner/work/opentofu/opentofu/internal/logging/panic.go:72
github.com/opentofu/opentofu/internal/backend/remote.(*Remote).Operation(0x4000923800, {0x1864540, 0x24905e0}, 0x40004dda40)
	/home/runner/work/opentofu/opentofu/internal/backend/remote/backend.go:827 +0x3b4
github.com/opentofu/opentofu/internal/backend/remote.TestRemote_planCanceled(0x4000a4f860)
	/home/runner/work/opentofu/opentofu/internal/backend/remote/backend_plan_test.go:116 +0xdc
testing.tRunner(0x4000a4f860, 0x145e758)
	/opt/hostedtoolcache/go/1.21.3/x64/src/testing/testing.go:[15](https://github.com/opentofu/opentofu/actions/runs/9061684941/job/24893979120#step:7:16)95 +0xe8
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.21.3/x64/src/testing/testing.go:1648 +0x33c
FAIL	github.com/opentofu/opentofu/internal/backend/remote	3.102s
```

TestInit_cancelModules test:
```
--- FAIL: TestInit_cancelModules (0.01s)
    init_test.go:1846: wrong error message
        should contain: Module installation was canceled by an interrupt signal
        got:
        
        Error: Error accessing remote module registry
        
          on main.tf line 1:
           1: module "foo" {
        
        Failed to retrieve available versions for module "foo" (main.tf:1) from
        registry.does.not.exist: failed to request discovery document: Get
        "https://registry.does.not.exist/.well-known/terraform.json": dial tcp:
        lookup registry.does.not.exist: no such host.
        
FAIL
FAIL	github.com/opentofu/opentofu/internal/command	51.422s
```

**Comment by diofeher** [comment]
Hey, I would like to work on this one!

Do you know anything that could help me reproduce this error?

**Comment by ollevche** [comment]
Hey @diofeher thanks for volunteering! Unfortunately, I don't have any useful info on reproducing the failure, other than traces. However, I am happy to answer any questions here or in the community slack to help you with the debugging.

**Comment by cam72cam** [comment]
I don't know that I've seen this in quite some time.  I wonder if some other work has resolved it or we have just been getting lucky?

https://github.com/opentofu/opentofu/actions/workflows/build.yml?query=branch%3Amain+is%3Afailure

Most of those failures are from darwin_arm64 running slowly and failing, #2043

**Comment by diofeher** [comment]
I couldn't reproduce this one too...

**Comment by cam72cam** [comment]
Ok, let's close this is can't reproduce for now and re-open if we notice the CI failures.  Thanks for taking a look @diofeher !
